apiVersion: v1
kind: Service
metadata:
  name: generator-app-service
  labels:
    app: generator-app
spec:
  type: LoadBalancer
  selector:
    app: generator-app
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
