apiVersion: apps/v1
kind: Deployment
metadata:
 name: generator
spec:
 replicas: 1 
 selector:
  matchLabels:
   app: generator
 template:
  metadata:
   labels:
    app: generator
  spec:
   containers:
   - name: generator
     image: localhost:5001/generator
     ports:
     - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: generator-service
  labels:
    app: generator
spec:
  type: LoadBalancer
  selector:
    app: generator
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
