apiVersion: apps/v1
kind: Deployment
metadata:
 name: signal-generator
spec:
 replicas: 1
 selector:
  matchLabels:
   app: signal-generator
 template:
  metadata:
   labels:
    app: signal-generator
  spec:
   containers:
   - name: signal-generator
     image: localhost:5001/signal-generator
