apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-system
spec:
  addresses:
  - 172.18.0.0-172.18.0.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.18.0.0-172.18.0.50
