apiVersion: apps/v1
kind: Deployment
metadata:
 name: processor-app-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: processor-app
 template:
  metadata:
   labels:
    app: processor-app
  spec:
   containers:
   - name: processor-app
     image: localhost:5001/processor-app
     ports:
     - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: processor-app-service
  labels:
    app: processor-app
spec:
  type: LoadBalancer
  selector:
    app: processor-app
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
