apiVersion: apps/v1
kind: Deployment
metadata:
 name: ingestor
spec:
 replicas: 1
 selector:
  matchLabels:
   app: ingestor
 template:
  metadata:
   labels:
    app: ingestor
  spec:
   containers:
   - name: ingestor
     image: localhost:5001/ingestor

